### ISSUE TITLE
Issue when opening some non i2p local network destinations

### ISSUE THREAD

**Issue by Ryemantis** [eyedeekay/I2P-in-Private-Browsing-Mode-Firefox#101]
Most non i2p local destinations seem to be properly ignored by the add-on but when I try to load my local Plex dashboard the address gets replaced with 127.0.0.1 and the tab gets put into a container making the dashboard unreachable. 
Looking at the Firefox console output it can be seen that Plex sees the server but cannot reach it if the I2p add-on is enabled. It seems like Plex is guilty of switching the address to loopback when there is no response from the server but once that happens the add-on gets triggered. I have a suspicion it has something to do with the add-on disabling WebGL but I'm not sure.

It would be nice to have some sort of setting or exception to allow dashboards such as Plex to be accessible.

**Comment by eyedeekay** [comment]
Hmm, I thought I had already fixed this, it's shouldn't be trying to isolate non-routerconsole URL's anymore. Can you confirm what version you are on for me, and are you accessing plex via app.plex.tv or via a server you host somewhere, like on your LAN?

**Comment by Ryemantis** [comment]
Apologies, I was on an older version. I no longer have this issue with the current version
