### ISSUE TITLE
Extension not triggered if i2p url includes a query string

### ISSUE THREAD

**Issue by Ryemantis** [eyedeekay/I2P-in-Private-Browsing-Mode-Firefox#102]
When trying to reach some i2p sites with a link that has a query string attached, the extension will not trigger and the destination will not resolve. The issue only seems to happen when trying to access an i2p location outside of any i2p containers but works fine if tab is already containerized for i2p. 

Example:
http://tracker2.postman.i2p/index.php?view=Main&reset=1&start=0&limit=20

The link above will not trigger the extension but http://tracker2.postman.i2p will work just fine.

**Comment by eyedeekay** [comment]
Ah I see what's going on here. I added a semi-complicated workaround for it the browser misdirecting I2P queries to the default search engine when a scheme was unspecified. It will be fixed soon.
