### ISSUE TITLE
I2P Control / Toopie

### ISSUE THREAD

**Issue by Shoalsteed** [eyedeekay/I2P-in-Private-Browsing-Mode-Firefox#108]
<img width="454" alt="Screen Shot 2021-05-26 at 1 50 17 PM" src="https://user-images.githubusercontent.com/50714166/119709618-6ad2c080-be2b-11eb-9d82-8b79f2096890.png">

Consider adding instructions with the UX to let people know that they need I2P Control enabled for Toopie to display network health. Perhaps "Enable I2P Control to use Toopie" with a link ?

**Comment by eyedeekay** [comment]
Didn't I hide toopie if i2pcontrol is off...

**Comment by eyedeekay** [comment]
toopie.html is hidden when i2pcontrol is turned off from now on. If you find your way to toopie.html by accident(I don't think it's possible) then what you will see is instructions for how to enable I2PControl. Probably this issue is closable then?

**Comment by Shoalsteed** [comment]
Yup - just looked and I no longer see the option. Closing the issue.
