### ISSUE TITLE
Proxy Ready Indicator

### ISSUE THREAD

**Issue by Shoalsteed** [eyedeekay/I2P-in-Private-Browsing-Mode-Firefox#113]
Shows a green circle when not ready. Goes away when ready
<img width="211" alt="Screen Shot 2021-10-27 at 5 14 21 PM" src="https://user-images.githubusercontent.com/50714166/139148315-b54d771e-d871-4222-b80a-4b977aedb929.png">
<img width="235" alt="Screen Shot 2021-10-27 at 5 16 45 PM" src="https://user-images.githubusercontent.com/50714166/139148410-9f671178-d52a-4c4f-89ef-8dc063a4e268.png">
 This is confusing since it is the opposite of the visual readiness workflow for the I2P router console.

**Comment by eyedeekay** [comment]
Oops, I've got an exclamation point somewhere it shouldn't be.

**Comment by eyedeekay** [comment]
fix on a branch
