### ISSUE TITLE
Torrent Download/Controls

### ISSUE THREAD

**Issue by Shoalsteed** [eyedeekay/I2P-in-Private-Browsing-Mode-Firefox#114]
<img width="451" alt="Screen Shot 2021-10-27 at 5 17 35 PM" src="https://user-images.githubusercontent.com/50714166/139148653-853ea34a-d609-4759-a603-30b8eaa5f1b4.png">

Clicked on "Download"
Nothing happens when I click web UI
Nothing happens when I try to search

**Comment by eyedeekay** [comment]
Search is an internal search, it filters which torrents you see from the list you have already downloaded by searching their text/metadata. If you do not have any torrents downloaded then it will not have anything to search. This is the intended behavior. Open the Web UI should launch you into snark, not sure why it isn't.
