### ISSUE TITLE
BrowserAction : Proxy Ready Indicator 

### ISSUE THREAD

**Issue by Shoalsteed** [eyedeekay/I2P-in-Private-Browsing-Mode-Firefox#118]
The Proxy Ready indicator shows up ( green dot ) when I open this, and then goes away. 
It makes me think that there is a connection issue. 
However, I have a working Java router and can access zzz's forum. 
So in fact, the proxy is working, but the indicator is not.

No proxy!!!
<img width="575" alt="Screen Shot 2022-09-27 at 4 27 58 PM" src="https://user-images.githubusercontent.com/50714166/192633171-141e859f-56b6-4db6-b3cc-e1dfd7e1e980.png">

But I got here!!!

<img width="575" alt="Screen Shot 2022-09-27 at 4 30 36 PM" src="https://user-images.githubusercontent.com/50714166/192633614-bee6543c-0993-4751-8ef1-e16adf8488c3.png">

**Comment by eyedeekay** [comment]
Fixed in 68f2de570292a6e026b7e1e429af4efe5714fb9a
