### ISSUE TITLE
BrowserAction: Control 

### ISSUE THREAD

**Issue by Shoalsteed** [eyedeekay/I2P-in-Private-Browsing-Mode-Firefox#120]
Change
"Create" to >  **"New I2P Browser Tab"** to describe the action more accurately.
"Close All" to >  **Close All I2P Browser Tabs**

Do the words I2P Browser in orange link to anything? For me it does not. 
If not, I would recommend changing the colour to the same as the text  ( black) so I do not expect an action.

<img width="527" alt="Screen Shot 2022-09-27 at 5 15 41 PM" src="https://user-images.githubusercontent.com/50714166/192637107-2e892927-3e07-45df-b9d9-da2f277a8de1.png">

**Comment by eyedeekay** [comment]
The orange text does not link to anything

**Comment by eyedeekay** [comment]
Fixed in: 66f56b4375b8361b62d3898b3c596f34316be208
