### ISSUE TITLE
Extension Page: Application Section 

### ISSUE THREAD

**Issue by Shoalsteed** [eyedeekay/I2P-in-Private-Browsing-Mode-Firefox#123]
"These applications work with I2P directly to provide them with security and privacy."

Should this not talk about the use of containers?
Ie " _Access the following I2P Java  applications and Services using the extra security provided by the containers feature_
Containers keep your activities safe by.....

The text in the links sections could be changed to more actionable less introduction. If a person needs a working Java router, they should be familiar with /home and what they can access and what those things do and are named.

**Before**:
<img width="946" alt="Screen Shot 2022-09-28 at 10 05 19 AM" src="https://user-images.githubusercontent.com/50714166/192804332-ca6bd6bf-c06e-43a5-bb1f-9b40c85bb3b4.png">

**Suggested Changes Example:**
<img width="938" alt="Screen Shot 2022-09-28 at 10 20 58 AM" src="https://user-images.githubusercontent.com/50714166/192806262-780f08f0-e39c-4a32-a49b-329c3d754a39.png">

**Comment by Shoalsteed** [comment]
<img width="1059" alt="Screen Shot 2022-09-28 at 2 16 17 PM" src="https://user-images.githubusercontent.com/50714166/192859370-04dfab07-8621-4096-ab1f-af92201f7847.png">

**Comment by Shoalsteed** [comment]
Hover colour added :

<img width="966" alt="Screen Shot 2022-09-28 at 2 23 34 PM" src="https://user-images.githubusercontent.com/50714166/192859662-48ce6934-ef32-4033-89df-faf273e356e5.png">

**Comment by Shoalsteed** [comment]
**I2P Java Router Access**
Access the following I2P Java applications and Services. Router console applications are handled  under their own origins and within their own contextual identity. This adds more protection to application usage by isolating each application and preventing other tabs ( ie social media, etc ) from fingerprinting or scripts. All tabs use identifying colours to keep track of your I2P workflow. 


**I2P Java Router Console**
Visit the homepage of your router console.

**Hidden Services Manager**
View Status messages, manage services and tunnel control.

**Email ( SusiMail)**
Access the  I2P webmail client.

**Bittorrent (Snark)**
Access the I2P network file sharing service.

**Comment by Shoalsteed** [comment]
- add in Application description section that any applications accessed in the router will make use of the container feature. 
- Anything that I2Pd people need to know for their workflow.

**Comment by eyedeekay** [comment]
Can I get some hex for these colors?

**Comment by Shoalsteed** [comment]
I can send you the whole css file today after I review it one more time.

**Comment by Shoalsteed** [comment]
[css.txt](https://github.com/eyedeekay/I2P-in-Private-Browsing-Mode-Firefox/files/9701232/css.txt)
