### ISSUE TITLE
Toopie HTML 

### ISSUE THREAD

**Issue by Shoalsteed** [eyedeekay/I2P-in-Private-Browsing-Mode-Firefox#127]
Even increasing my screen size does not help. It looks like this.

<img width="269" alt="Screen Shot 2022-09-30 at 4 33 21 PM" src="https://user-images.githubusercontent.com/50714166/193352479-1d5210aa-3471-4904-8678-60573e701adc.png">

**Comment by eyedeekay** [comment]
These screenshots reflect the changes to very-narrow windows so far(WIP) and the workaround:

![drag-sidebar-after](https://user-images.githubusercontent.com/8733713/193477128-921e9482-5d21-4a0a-b299-6207731f8f5f.png)
![drag-sidebar](https://user-images.githubusercontent.com/8733713/193477132-0f8e14d7-c43c-4cd0-885f-5413fedae63f.png)

**Comment by eyedeekay** [comment]
Not sure how much better I'm going to be able to do than I'm doing at a certain point. I think it's as tolerant of narrow windows as I can reasonably make it.

**Comment by Shoalsteed** [comment]
Okay!

**Comment by Shoalsteed** [comment]
Should we close this issue?

**Comment by eyedeekay** [comment]
Yup.
