### ISSUE TITLE
Extension Page: Onboarding Section 

### ISSUE THREAD

**Issue by Shoalsteed** [eyedeekay/I2P-in-Private-Browsing-Mode-Firefox#130]
Change this section:
<img width="503" alt="Screen Shot 2022-10-05 at 6 44 01 PM" src="https://user-images.githubusercontent.com/50714166/194177300-8b625ea6-f9f4-4d9e-9782-18649e8f2fd3.png">

**About I2P In Private Browsing Mode**

**Protect Your Privacy** 
When using I2P In Private Browsing Mode,  you are protected against tracking and surveillance.The I2P Browser isolates cookies and deletes your browser history after your session. These modifications ensure your privacy and security are protected as your browse.

**I2P Network Browsing and Non-I2P Network Browsing**
This extension works automatically when you are browsing I2P sites. If you want to use I2P as a proxy to non-I2P sites, use the I2P In Private Browsing button in the toolbar and click New I2P Browser Tab to switch to I2P Browsing in a new tab.
Your experience while browsing the internet may be a little different. Things may be a bit slower, and depending on your security level, some elements may not work or load. You may also be asked to prove you are a human and not a robot. **Please note that you will need to configure the I2P outproxy function manually unless you are using the I2P Java Windows Easy Installer. Learn more here https://geti2p.net/en/about/browser-config.**

**Protecting Network Boundaries**
I2P is normally administered via a WebUI(The "Router Console"), which the user sometimes views in the same browser they use to visit remote sites. It is essential to prevent sites from being able to access information from this WebUI and other locally running sites.
Clearnet sites remain in the firefox-default container, but as soon as the firefox-default container requests a *.onion or *.i2p site, it will be instantly containerized. Tor Browser's identity management tooling controls clearnet tabs, and they are proxied using the default I2P outproxy or outproxy plugin.

**JS Restrictor**
Prevents any non-local host from using Javascript to connect to the localhost.

**I2P in Private Browsing**
Places I2P browsing into its own Container Tab where requests to *.onion resources are automatically dropped.

**Onion in Container Tabs**
Places .onion browsing into its own Container Tab where requests to *.i2p resources are automatically dropped.

**uBlock Origin**
Block ads, and by extension much malvertising. Reduces the potential of an attacker using an advertising network to deliver an attack to I2P users. Prevents ad networks from using their reach to build profiles of I2P users.

**LocalCDN** (Fork of Decentraleyes)
 LocalCDN acts as a cache of resources which would normally be provided by CDN's operated by companies that operate on the clearnet. Using LocalCDN for your browsing prevents a malfunctioning outproxy from affecting site functionality, decreases the load on outproxy operators, and improves UX by making sites load faster.

**Comment by eyedeekay** [comment]
I just made a huge change to how all of this text is implemented in practice and I need to re-group a little on the implementation side of things. See: https://github.com/eyedeekay/I2P-in-Private-Browsing-Mode-Firefox/issues/128 for more details, but the good news is that changing the text that we present to users just got a lot easier. All the changes we need to make **only** need to happen in the `_localhost/*/messages.json` files from now on, and it now has as far as I can tell 100% coverage for translatable sections.

**Comment by eyedeekay** [comment]
Text is checked in.
