### ISSUE TITLE
Outproxy Config

### ISSUE THREAD

**Issue by Shoalsteed** [eyedeekay/I2P-in-Private-Browsing-Mode-Firefox#131]
add any info people may need for outproxy.

**Comment by eyedeekay** [comment]
Only people who have used `false.i2p` in the past will need this: http://geti2p.net//en/blog/post/2022/8/4/Enable-StormyCloud otherwise, nothing is required.

**Comment by Shoalsteed** [comment]
okay - I am thinking that nobody will be using false i2p anymore, so closing the issue.
