### ISSUE TITLE
Duplicate Icon 

### ISSUE THREAD

**Issue by Shoalsteed** [eyedeekay/I2P-in-Private-Browsing-Mode-Firefox#135]
Reviewing the descriptions of the icons in the guide I found that the HTTPS indicators are one purple and one green? Can we double check this.

**Comment by eyedeekay** [comment]
Can you post a screenshot?

**Comment by Shoalsteed** [comment]
itoopiebt and itoopiesbt: 

<img width="363" alt="Screen Shot 2022-10-24 at 2 07 20 PM" src="https://user-images.githubusercontent.com/50714166/197595395-d436bb56-09b8-40bb-8ede-e9be1316bf6e.png">
<img width="347" alt="Screen Shot 2022-10-24 at 2 06 58 PM" src="https://user-images.githubusercontent.com/50714166/197595421-27869331-57e4-4cc6-9098-ba3e7d840557.png">

It may be a good idea to name the icons for their function?

**Comment by Shoalsteed** [comment]
Maybe name png's like this: 

![Style Guide final ](https://user-images.githubusercontent.com/50714166/197596036-af37c15f-a601-46a1-b50f-8c6bdb5c8e4e.png)

**Comment by Shoalsteed** [comment]
![infotoopiesbt](https://user-images.githubusercontent.com/50714166/197610514-bccd401c-d51a-4c0e-bf53-f239e08ed963.png)

here it is so you don't have to hunt for it

**Comment by eyedeekay** [comment]
Fixed on main, will cut a release this evening to fix.

**Comment by Shoalsteed** [comment]
fixed.
