### ISSUE TITLE
Installing addon breaks website

### ISSUE THREAD

**Issue by CocolinoFan** [eyedeekay/I2P-in-Private-Browsing-Mode-Firefox#142]
Hello,
Installing the addon breaks [adsbexchange](https://globe.adsbexchange.com/) for me.
I get a `Problem fetching data from the server: 403` on my computer and my phone.

Computer: Ubuntu 24.04 | Firefox 130.0 (64-bit) Flatpak
Phone: PureOS byzantium | Firefox 115.15.Oesr (64-bit) normal apt install
I2P in Private Browsing Mode version: 2.6.0

**Comment by CocolinoFan** [comment]
Is also breaks live streams on https://odysee.com

**Comment by CocolinoFan** [comment]
It also breaks online payments... I am unable to pay by card online after installing the addon.

**Comment by eyedeekay** [comment]
Thanks for the report. I'm sure the addon is the only thing that has changed, but I need help reproducing the behavior.

Re: on your phone: I am confused how you managed to get it installed on your phone at all. The API's and manifest keys used in this plugin are not available in the Android version. I have to work pretty hard to even get it to a state where I can test the availability of the API's in Firefox mobile. I'm pretty sure it can't be my fault on your phone.

Re: on your desktop: The addon enables the limited privacy features enabled by the Mozilla webextensions API, some of which are by necessity enabled browser-wide, including resistFingerprinting, disabling third-party cookies, etc. My hypothesis is that one of these is the culprit. I don't use either of these services, so I'll have to find a way to test them. Odysee is simple enough to test. Dunno about adsbexchange.

**Comment by CocolinoFan** [comment]
Thank you for your time sir.
I should have mentioned I have a Linux phone. It was confusing at first, as I only installed the add-on on my computer. But I see now that I am logged in with the same account on both devices. and Firefox installs add-ons on all the browsers you are logged into.
I'm not bothered that much. I mean, 99% of the internet works with the add-on.
What makes things difficult is that, you have an option in Firefox for add-ons called "Run in Private Windows" "Allow" or "Don't Allow". I have it on "Don't Allow" so that if I need to use something that does not work with the add-on I do it in a Private Window. Problem is, even in Private Windows, with the add-on not running, the websites are still broken, I have to completely delete the add-on, do my work, and then install it again.
P.S. I am not particularly intelligent, but I can for sure help with testing :3

**Comment by eyedeekay** [comment]
I believe you and #143 have been experiencing related issues. Please stand by for the next release to test if both issues are fixed.

**Comment by eyedeekay** [comment]
Thanks, that's important information to have.
