### ISSUE TITLE
addon breaks login to the archlinux aur

### ISSUE THREAD

**Issue by Simbi0z** [eyedeekay/I2P-in-Private-Browsing-Mode-Firefox#143]
While the addon is enabled I get

> 400 - Bad Request
> 
> Bad Referer header.

When I try to login to the aur:

https://aur.archlinux.org/

**Comment by eyedeekay** [comment]
OK I'll make an aur account and figure our what I can do.

**Comment by eyedeekay** [comment]
Hm. Some mysteries involved here still, I am able to log into the AUR using my daily driver Firefox+I2PIPB with my newly created AUR account. Let's try and narrow it down a bit more:

1.  What is your Firefox version?
2. Are you using a Firefox variant(Icecat, LibreWolf, etc)?
3. Are you in a "regular" tab or an "I2P Browsing" tab?
4. Have you modified about:config?
5. Are you using any other extensions?

**Comment by Simbi0z** [comment]
Distro: archlinux
Name            : firefox-developer-edition
Version         : 131.0b9-1

step 1:  run firefox with parameter
firefox --ProfileManager
step 2: create new profile
step 3: download extension from 
https://addons.mozilla.org/en-US/firefox/addon/i2p-in-private-browsing/
Don't install any other extension, don't modify about:config.
step 4: change default homepage, new windows and tabs to "Firefox Home (default)", so we can also browse the normal web.
step 5: go to https://aur.archlinux.org/, login

result:
![2024-09-28T21:26:01,572135619-03:00](https://github.com/user-attachments/assets/ed4d3f4b-113e-4e96-8a7e-b9fc8bd807ce)

**Comment by eyedeekay** [comment]
Issue found and fixed on master. Release will be made soon.

**Comment by eyedeekay** [comment]
Release today should have the fix out to users. Please let me know if it works so I can close the issue.

**Comment by eyedeekay** [comment]
Observed to be fixed here. Please re-open if the issue recurs.
