### ISSUE TITLE
FoxyProxy Compatibility?

### ISSUE THREAD

**Issue by eyedeekay** [eyedeekay/I2P-in-Private-Browsing-Mode-Firefox#47]
This extension currently *Breaks the expected behavior of FoxyProxy* by enforcing it's rules over those described by FoxyProxy. This one might be more trouble than it's worth, in fact I think it probably is, but if it isn't, this is a nice-to-have for some of the longtime Foxy users to ease their transition.

**Comment by eyedeekay** [comment]
What's the desirable behavior here and how do we get to it? I think what we might need to do is be able to *ask* FoxyProxy if the URL we're getting matches a pattern it recognizes and respond back with the proxy object we need to actually use. That might require reading FoxyProxy's storage, or maybe implementing an API in FoxyProxy that we can talk to? These are some things to think about, people have pretty elaborate FoxyProxy configurations that are working for them, it would be nice if we could work together.

**Comment by Thinkablemell0w** [comment]
Does it really make sense to add support for that?
I mean is there anyone who does have both installed and if so why would one do that ?

**Comment by eyedeekay** [comment]
Mostly I'm thinking legacy users? Like there are a *lot* of people using FoxyProxy for I2P right now, the configurations they use are inconsistent at best and sometimes highly customized. What's worse is that sometimes it might even be customized for a sane and valid reason. So if they want to keep using FoxyProxy, but also have a menu full of shortcuts and a proxy readiness indicator and protocol handlers for bittorrent and Snark-RPC integration, then they have to do that piecemeal with other extensions.

**Comment by Thinkablemell0w** [comment]
I see, thanks for clarifying
