### ISSUE TITLE
Cant reach /home

### ISSUE THREAD

**Issue by danrobi11** [eyedeekay/I2P-in-Private-Browsing-Mode-Firefox#92]
Running extension 0.70 with firefox esr 68.6.0, i2p+ and muwire plugin
https://open.lbry.com/@Danrobi:b/bug-extension-0.70-2020-03-24_02.02.27:1

**Comment by eyedeekay** [comment]
Oh my god. I took a look and saw it immediately. The fix I pushed was broken. I'll have a new release in less than an hour.

**Comment by danrobi11** [comment]
@eyedeekay  
Working perfectly now. Disable/enable also fixed, good job!

**Comment by eyedeekay** [comment]
Cool, closing
