### ISSUE TITLE
Something strange going on with Twitter logins

### ISSUE THREAD

**Issue by eyedeekay** [eyedeekay/I2P-in-Private-Browsing-Mode-Firefox#98]
There is a chance this extension may be breaking Twitter logins in some circumstances. How is not immediately apparent to me from the information I have, however it's infinitely redirecting people which could either arise from the outproxy configuration, or Twitter sign-on is broken because some aspect of it is being blackholed or redirected mistakenly by the webextension. Or maybe Twitter's wrong, but they have a bigger staff than me so I'll assume I'm wrong first.

**Comment by eyedeekay** [comment]
ping @DarkerStar @Twitter https://twitter.com/IndiInTheWired/status/1260541219714863104

**Comment by eyedeekay** [comment]
@twitter this is **substantially** complicated by the fact that I cannot sign up for an account without using a phone number.

**Comment by Shoalsteed** [comment]
I tried to login myself - chose "i2pbrowser" from New Container tab. It set off Twitter  2 factor and then hung 
<img width="486" alt="Screen Shot 2020-05-13 at 2 41 27 PM" src="https://user-images.githubusercontent.com/50714166/81851926-36de7300-9528-11ea-987d-d176640c0fd2.png">

**Comment by Shoalsteed** [comment]
<img width="416" alt="Screen Shot 2020-05-13 at 2 44 51 PM" src="https://user-images.githubusercontent.com/50714166/81852104-80c75900-9528-11ea-8429-49a4ba1e255d.png">

**Comment by eyedeekay** [comment]
Bummer, that means this might not be my fault and if it's not my fault it means I can't fix it. If twitter consider's the outproxy suspicious then there's not much I can do. The if there is an infinite redirect thing still happening I'm still going to try and address that though.

**Comment by eyedeekay** [comment]
Does not appear to have been an issue on my end. Have reports of successful twitter use, although I cannot use Twitter myself for non-I2P related reasons. Closing.
